       //IMPORTACION DE LIBRERIAS
  #include <iostream.h>
  #include <conio.h>
  #include <stdlib.h>
  #include <stdio.h>

        int inicial;
                                                                                                                                                                         //IMPORTACION DE LIBRERIAS
  #include <iostream.h>
  #include <conio.h>
  #include <stdlib.h>
  #include <stdio.h>
     int promedio;
     int suma;
     int contar;


  void main(){
   cout<<" ingrese el numero a promediar:\n";
   cin>> promedio;

    do{
     contar=contar+contar;
     cout<<"   ingrese los numeros \n"
     <<contar; }

     while(suma=contar/promedio);{
    cout<<"\n   el promedio de tu proyecto es: "<<suma;
    }


    getch();

  }
